"""Discover shard list — GENERATED BY pipeline/tools/gen_python.py."""

from __future__ import annotations

ALL_SHARDS: tuple[str, ...] = (
    "aws_aurora",
    "aws_cloudfront",
    "aws_dynamodb",
    "aws_ebs",
    "aws_ec2",
    "aws_eks",
    "aws_elasticache",
    "aws_lambda",
    "aws_opensearch",
    "aws_rds",
    "aws_s3",
    "azure_aks",
    "azure_appservice",
    "azure_blob",
    "azure_cosmosdb",
    "azure_disks",
    "azure_functions",
    "azure_mariadb",
    "azure_mysql",
    "azure_postgres",
    "azure_redis",
    "azure_sql",
    "azure_vm",
    "gcp_bigquery",
    "gcp_cloud_sql",
    "gcp_functions",
    "gcp_gce",
    "gcp_gcs",
    "gcp_gke",
    "gcp_memorystore",
    "gcp_run",
    "gcp_spanner",
    "openrouter",
)

_PROVIDER_OF: dict[str, str] = {
    "aws_aurora": "aws",
    "aws_cloudfront": "aws",
    "aws_dynamodb": "aws",
    "aws_ebs": "aws",
    "aws_ec2": "aws",
    "aws_eks": "aws",
    "aws_elasticache": "aws",
    "aws_lambda": "aws",
    "aws_opensearch": "aws",
    "aws_rds": "aws",
    "aws_s3": "aws",
    "azure_aks": "azure",
    "azure_appservice": "azure",
    "azure_blob": "azure",
    "azure_cosmosdb": "azure",
    "azure_disks": "azure",
    "azure_functions": "azure",
    "azure_mariadb": "azure",
    "azure_mysql": "azure",
    "azure_postgres": "azure",
    "azure_redis": "azure",
    "azure_sql": "azure",
    "azure_vm": "azure",
    "gcp_bigquery": "gcp",
    "gcp_cloud_sql": "gcp",
    "gcp_functions": "gcp",
    "gcp_gce": "gcp",
    "gcp_gcs": "gcp",
    "gcp_gke": "gcp",
    "gcp_memorystore": "gcp",
    "gcp_run": "gcp",
    "gcp_spanner": "gcp",
    "openrouter": "openrouter",
}


def provider_of(shard: str) -> str:
    try:
        return _PROVIDER_OF[shard]
    except KeyError as exc:
        raise KeyError(shard) from exc
