"""Per-shard compressed-byte budgets enforced by the manifest builder.

GENERATED BY pipeline/tools/gen_python.py — DO NOT EDIT.
Edit `pipeline/shards/<shard>.yaml` and run `make generate-python`.

Overflow policy: hard fail. When a shard exceeds its budget, the manifest
build raises BudgetExceeded and the daily workflow fails. The forced human
decision — raise the budget, split the shard, or narrow the scope — is the
entire point.
"""

from __future__ import annotations


SHARD_BUDGETS: dict[str, int] = {
    'aws_aurora':            10_000_000,
    'aws_cloudfront':           500_000,
    'aws_dynamodb':             500_000,
    'aws_ebs':                  500_000,
    'aws_ec2':               40_000_000,
    'aws_elasticache':        5_000_000,
    'aws_lambda':               500_000,
    'aws_rds':               10_000_000,
    'aws_s3':                   500_000,
    'azure_blob':               500_000,
    'azure_cosmosdb':         5_000_000,
    'azure_disks':            3_000_000,
    'azure_functions':          500_000,
    'azure_mariadb':            500_000,
    'azure_mysql':            3_000_000,
    'azure_postgres':         3_000_000,
    'azure_redis':            3_000_000,
    'azure_sql':              3_000_000,
    'azure_vm':              40_000_000,
    'gcp_cloud_sql':          3_000_000,
    'gcp_functions':            500_000,
    'gcp_gce':                6_000_000,
    'gcp_gcs':                  500_000,
    'gcp_run':                  500_000,
    'gcp_spanner':            5_000_000,
    'openrouter':             1_000_000,
}


class BudgetExceeded(Exception):
    """Raised by check_shard_size when compressed_bytes > budget."""


def check_shard_size(*, shard: str, compressed_bytes: int) -> None:
    if shard not in SHARD_BUDGETS:
        raise KeyError(f"no budget configured for shard {shard!r}")
    budget = SHARD_BUDGETS[shard]
    if compressed_bytes > budget:
        raise BudgetExceeded(
            f"shard {shard!r} exceeds budget: {compressed_bytes:,} bytes "
            f"(budget {budget:,}). Either raise the budget in "
            f"pipeline/shards/{shard}.yaml, split the shard, or narrow scope."
        )
