// Code generated by tools/gen_go_tier_tokens.py; DO NOT EDIT.

package estimate

import "fmt"

var TierTokensCount = map[string]float64{
	"0": 0e0,
	"100": 100e0,
	"100B": 100000000000e0,
	"100M": 100000000e0,
	"10B": 10000000000e0,
	"10K": 10000e0,
	"13M": 13000000e0,
	"19B": 19000000000e0,
	"1B": 1000000000e0,
	"1M": 1000000e0,
	"200B": 200000000000e0,
	"20B": 20000000000e0,
	"25": 25e0,
	"2500M": 2500000000e0,
	"250M": 250000000e0,
	"300M": 300000000e0,
	"333M": 333000000e0,
	"5B": 5000000000e0,
	"667M": 667000000e0,
}

var TierTokensBytes = map[string]float64{
	"0": 0e0,
	"100GB": 100000000000e0,
	"100TB": 100000000000000e0,
	"10TB": 10000000000000e0,
	"150TB": 150000000000000e0,
	"1PB": 1000000000000000e0,
	"1TB": 1000000000000e0,
	"40TB": 40000000000000e0,
	"500GB": 500000000000e0,
	"500TB": 500000000000000e0,
	"50TB": 50000000000000e0,
	"5PB": 5000000000000000e0,
}

// ParseCountTier returns the lower-bound count for a count-domain tier token.
func ParseCountTier(token string) (float64, error) {
	v, ok := TierTokensCount[token]
	if !ok {
		return 0, fmt.Errorf("ParseCountTier: token %q not in TierTokensCount", token)
	}
	return v, nil
}

// ParseBytesTier returns the lower-bound bytes for a bytes-domain tier token.
func ParseBytesTier(token string) (float64, error) {
	v, ok := TierTokensBytes[token]
	if !ok {
		return 0, fmt.Errorf("ParseBytesTier: token %q not in TierTokensBytes", token)
	}
	return v, nil
}
