#!/usr/bin/env python3
"""Generate internal/estimate/tiertokens.go from pipeline/normalize/tier_tokens.py."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "pipeline"))

from normalize.tier_tokens import (
    TIER_TOKENS_COUNT, TIER_TOKENS_BYTES,
    parse_count_tier, parse_bytes_tier,
)

OUTPUT = Path(__file__).parent.parent / "internal" / "estimate" / "tiertokens.go"


def _fmt_float(v: float) -> str:
    """Format a float as a Go float64 literal."""
    if v == int(v):
        return f"{int(v)}e0"
    return repr(v)


def _fmt_map(name: str, tokens: frozenset[str], parser) -> str:
    entries = []
    for t in sorted(tokens):
        v = parser(t)
        entries.append(f'\t"{t}": {_fmt_float(v)},')
    return "var " + name + " = map[string]float64{\n" + "\n".join(entries) + "\n}"


def render_go_code() -> str:
    """Return the generated Go source as a string (without writing to disk)."""
    count_map = _fmt_map("TierTokensCount", TIER_TOKENS_COUNT, parse_count_tier)
    bytes_map = _fmt_map("TierTokensBytes", TIER_TOKENS_BYTES, parse_bytes_tier)

    return f"""// Code generated by tools/gen_go_tier_tokens.py; DO NOT EDIT.

package estimate

import "fmt"

{count_map}

{bytes_map}

// ParseCountTier returns the lower-bound count for a count-domain tier token.
func ParseCountTier(token string) (float64, error) {{
\tv, ok := TierTokensCount[token]
\tif !ok {{
\t\treturn 0, fmt.Errorf("ParseCountTier: token %q not in TierTokensCount", token)
\t}}
\treturn v, nil
}}

// ParseBytesTier returns the lower-bound bytes for a bytes-domain tier token.
func ParseBytesTier(token string) (float64, error) {{
\tv, ok := TierTokensBytes[token]
\tif !ok {{
\t\treturn 0, fmt.Errorf("ParseBytesTier: token %q not in TierTokensBytes", token)
\t}}
\treturn v, nil
}}
"""


def main() -> None:
    go_code = render_go_code()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(go_code)
    print(f"Generated {OUTPUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
